//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.16 at 03:10:34 PM CET 
//

@XmlSchema(elementFormDefault = XmlNsForm.UNQUALIFIED,
        xmlns = {
                @XmlNs(prefix = "xsi", namespaceURI = "http://www.w3.org/2001/XMLSchema-instance"),
                @XmlNs(prefix = "toolkit", namespaceURI = "http://oai.dlib.vt.edu/OAI/metadata/toolkit"),
                @XmlNs(prefix = "oai_dc", namespaceURI = "http://purl.org/dc/elements/1.1/")
        }) package org.onehippo.forge.oaipmh.provider.model.oai;
import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;